runtime: java11
entrypoint: java -Xmx64m -jar blahblah.jar
env: standard
instance_class: F1
handlers:
  - url: .*
    script: auto
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic
service_account: summer-prism-379110@appspot.gserviceaccount.com